### PR TITLE
Align viewer with altair repo

### PR DESCRIPTION
**Pull request by mattijn**
This PR:
- align the `INLINE_HTML` variable with the current Altair repo counterpart

### CODE REVIEW

**Review by jakevdp — COMMENTED** [review]
Have you tested this? We don't have any automated test coverage of javascript rendering, so it will be important to test manually.

In particular, I'm concerned about the removal of the code that strips `js` from the paths when running under `requirejs`. Are you certain that's no longer necessary?

**Comment by mattijn** [comment]
I've tested locally, but I can understand if we want to test this more scrupulously in different environments.

**Comment by timonviola** [comment]
I have the same issue and would be happy to render some examples if that helps merging this.
@jakevdp what tests do you have in mind?

**Comment by joelostblom** [comment]
Since Altair 5.3, the functionality of Altair Viewer is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package instead. See [the docs on how to use the browser renderer](https://altair-viz.github.io/user_guide/display_frontends.html#browser-renderer) to display charts via `.show()`, and the PR https://github.com/altair-viz/altair/pull/3379 for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for rendering charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.

**Pull request closed without merging**
