### PR TITLE
Update to Vega-Lite version 5.2.0

### PR DESCRIPTION
**Pull request by mattijn**
This PR:
- adds the Vega-Lite bundle version 5.2.0 and updates the Vega-Embed bundle to version 6.20.5.

One question, do we want to keep adding new bundles without removing previous bundles?

### CODE REVIEW

**Comment by jakevdp** [comment]
Looks good. Would you mind doing the Python version bumps as part of a separate PR? (I like to keep orthogonal changes separate where possible)

**Comment by jakevdp** [comment]
Regarding old versions... Altair doesn't pin any particular version of altair_viewer, so if we drop them then users of old Altair versions may find that their code doesn't work any more. There's very little cost to keeping old versions around, so I think we should keep doing that until there's a good reason to do different.

**Comment by mattijn** [comment]
Some back and forth, but I think this PR is good to go now.

**Comment by jakevdp** [comment]
Did you deliberately update the javascript in `_viewer.py`?

**Comment by mattijn** [comment]
Yes, the reasoning was to align it with the recent changes in altair. Can revert if you think this is not needed.

**Comment by jakevdp** [comment]
Oh, that makes sense.

Can you do that as a separate PR as well? It's just easier book-keeping since it's not directly related to the bundled javascript versions.

**Review by jakevdp — APPROVED** [review]

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
